/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import util.ManipularArquivos;

/**
 *
 * @author aleff
 */
public class TelaAutenticação extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaAutenticação
     */
    public TelaAutenticação() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfNAutentic = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfMensagem = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfPeriodo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        rbtTrue = new javax.swing.JRadioButton();
        rbtFalse = new javax.swing.JRadioButton();
        btGravar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Autenticação");

        jLabel1.setText("Nº de Autenticações:");

        jLabel2.setText("Mensagem:");

        jLabel3.setText("Período(h):");

        jLabel4.setText("Casesensitive:");

        rbtTrue.setText("true");

        rbtFalse.setText("false");

        btGravar.setText("Gravar");
        btGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGravarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(tfPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel4)
                        .addGap(26, 26, 26)
                        .addComponent(rbtTrue)
                        .addGap(27, 27, 27)
                        .addComponent(rbtFalse)
                        .addGap(37, 37, 37)
                        .addComponent(btGravar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(tfNAutentic, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(tfMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfNAutentic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(tfMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(rbtTrue)
                    .addComponent(rbtFalse)
                    .addComponent(btGravar))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGravarActionPerformed
        String path = "/home/aleff/squid.conf";

        if (rbtTrue.isSelected()) {
            String texto = "auth_param basic realm " + tfMensagem.getText() + "\n"
                    + "auth_param basic program /usr/lib/squid3/basic_ncsa_auth /etc/squid3/passwd\n"
                    + "auth_param basic children " + tfNAutentic.getText() + "\n"
                    + "auth_param basic credentialsttl " + tfPeriodo.getText() + " hours\n"
                    + "auth_param basic casesensitive on\n"
                    + "acl password proxy_auth REQUIRED\n"
                    + "http_access allow password\n"
                    + "http_access deny all\n\n";
            
            new ManipularArquivos().gravar(path, texto);
        }

        if (rbtFalse.isSelected()) {
            String texto = "auth_param basic realm " + tfMensagem.getText() + "\n"
                    + "auth_param basic program /usr/lib/squid3/basic_ncsa_auth /etc/squid3/passwd\n"
                    + "auth_param basic children " + tfNAutentic.getText() + "\n"
                    + "auth_param basic credentialsttl " + tfPeriodo.getText() + " hours\n"
                    + "auth_param basic casesensitive off\n"
                    + "acl password proxy_auth REQUIRED\n"
                    + "http_access allow password\n"
                    + "http_access deny all\n\n";
            
            new ManipularArquivos().gravar(path, texto);
        }
    }//GEN-LAST:event_btGravarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btGravar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton rbtFalse;
    private javax.swing.JRadioButton rbtTrue;
    private javax.swing.JTextField tfMensagem;
    private javax.swing.JTextField tfNAutentic;
    private javax.swing.JTextField tfPeriodo;
    // End of variables declaration//GEN-END:variables
}
